export const buildingCodes = [
    { code: 'A0', description: 'A0: Cape Cod' },
    { code: 'A1', description: 'A1: Dos pisos - Independiente, tamaño pequeño o mediano' },
    { code: 'A2', description: 'A2: Una planta - Vivienda permanente' },
    { code: 'A3', description: 'A3: Residencia suburbana grande' },
    { code: 'A4', description: 'A4: Residencia urbana unifamiliar' },
    { code: 'A5', description: 'A5: Vivienda unifamiliar adosada o semiadosada' },
    { code: 'A6', description: 'A6: Cabaña de verano' },
    { code: 'A7', description: 'A7: Mansión o casa adosada' },
    { code: 'A9', description: 'A9: Unifamiliar miscelánea' },
    { code: 'B1', description: 'B1: Bifamiliar de ladrillo' },
    { code: 'B2', description: 'B2: Bifamiliar de madera' },
    { code: 'B3', description: 'B3: Bifamiliar convertida desde unifamiliar' },
    { code: 'B9', description: 'B9: Bifamiliar miscelánea' },
    { code: 'C0', description: 'C0: Tres familias' },
    { code: 'C3', description: 'C3: Cuatro familias' },
    { code: 'C6', description: 'C6: Cooperativa sin ascensor' },
    { code: 'C8', description: 'C8: Cooperativa sin ascensor; conversión desde loft/almacén' },
    { code: 'D0', description: 'D0: Cooperativa con ascensor; conversión desde loft/almacén' },
    { code: 'D4', description: 'D4: Cooperativa con ascensor' },
    { code: 'R1', description: 'R1: Unidad residencial en edificio de 2 a 10 unidades' },
    { code: 'R2', description: 'R2: Unidad residencial en edificio sin ascensor' },
    { code: 'R3', description: 'R3: Unidad residencial en edificio de 1 a 3 pisos' },
    { code: 'R4', description: 'R4: Unidad residencial en edificio con ascensor' },
    { code: 'R6', description: 'R6: Unidad residencial en edificio de 1 a 3 unidades - Clase 1 original' },
    { code: 'R8', description: 'R8: Unidad comercial en edificio de 2 a 10 unidades' },
    { code: 'R9', description: 'R9: Cooperativa dentro de un condominio' }
  ];